version: "3.7"

services:
  dina-db:
    image: "postgres:10"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: pguser

  init-db:
    image: "aafcbicoe/dina-db-init-container:dev"
    environment:
#     the database and the user must already be set on the Postgres server
      POSTGRES_DB: my_db
      POSTGRES_PASSWORD: pg1234
      POSTGRES_HOST: dina-db
      POSTGRES_USER: pguser

#      v2 example
#      USE_V2: true
#      DB_USER: keycloak_user
#      DB_PASSWORD: kjasfkjfekjef

#      to create a new database
#      DB_NAME: my_db2

      DINA_DB: agent collection

      PREFIX_agent: xzy
      MIGRATION_USER_agent: migration_user_agent
      MIGRATION_USER_PW_agent: muagent123
      WEB_USER_agent: web_user_agent
      WEB_USER_PW_agent: wuagent321

      PG_EXTENSION_collection: pgcrypto
      MIGRATION_USER_collection: migration_user_collection
      MIGRATION_USER_PW_collection: mucoll123
      WEB_USER_collection: web_user_collection
      WEB_USER_PW_collection: wucoll321

    depends_on:
      - "dina-db"
