version: "3.7"

services:
  dina-db:
    image: "postgres:12"
    environment:
      POSTGRES_DB: dina
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: pguser

  init-db:
    build: .
    environment:
      POSTGRES_DB: dina
      POSTGRES_PASSWORD: pg1234
      POSTGRES_HOST: dina-db
      POSTGRES_USER: pguser

      DINA_DB: agent collection

      MIGRATION_USER_agent: migration_user_agent
      MIGRATION_USER_PW_agent: muagent123
      WEB_USER_agent: web_user_agent
      WEB_USER_PW_agent: wuagent321

      PG_EXTENSION_collection: pgcrypto postgis
      MIGRATION_USER_collection: migration_user_collection
      MIGRATION_USER_PW_collection: mucoll123
      WEB_USER_collection: u
      WEB_USER_PW_collection: u

    depends_on:
      - "dina-db"
