name: Build Docker Image and Push to DockerHub

on: [push]

jobs:
  push:
    name: Build Docker Image and Push
    runs-on: ubuntu-latest
    env:
      push_to_docker_hub: true
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set VERSION_TAG ENV variable
        run: |
          echo "VERSION_TAG=$(cat version.txt)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: env.push_to_docker_hub == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push
        if: env.push_to_docker_hub == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aafcbicoe/dina-db-init-container:${{ env.VERSION_TAG }}
          provenance: false
